### ISSUE TITLE
webcam has issue staying on if you leave the browser tab

### ISSUE THREAD

**Issue by CobyKabili** [Robo3D/OctoPrint-robotheme#12] opened 2017-06-02 17:07 UTC
I started a live stream on an R2. Refreshed the page, and saw the video stream come up. Worked.

I then clicked on another borwser tab (gmail for ex) and then went back to octoprint tab, the webcam shut off and i had to refresh the page to get it back up.

Is this a bug? or is this meant so it wont take up bandwidth when you arent looking at it?

**Comment by victorevector** [comment] 2017-06-02 17:56
`I then clicked on another borwser tab (gmail for ex) and then went back to octoprint tab, the webcam shut off and i had to refresh the page to get it back up.`

Did you have to click "Start Webcam" again or just refresh the web page?

**Comment by CobyKabili** [comment] 2017-06-02 18:00
@victorevector just refresh the page

**Comment by victorevector** [comment] 2017-06-02 18:03
Good insight @CobyKabili. I don't have any answers to your questions right now but I'm sure we'll find answers once we start engineering this rework. In the meantime, let's keep this issue open so we can reference it during our development cycle.

**Comment by victorevector** [comment] 2017-06-09 00:47
this is a duplicate of this https://github.com/Robo3D/OctoPrint-robotheme/issues/11

**Closed** 2017-06-09 00:47 UTC
